"""
This type stub file was generated by pyright.
"""

import sys
from django.views.generic import View
from markdown.preprocessors import Preprocessor

"""
The `compat` module provides support for backwards compatibility with older
versions of Django/Python, and compatibility wrappers around optional packages.
"""
def get_original_route(urlpattern):
    """
    Get the original route/regex that was typed in by the user into the path(), re_path() or url() directive. This
    is in contrast with get_regex_pattern below, which for RoutePattern returns the raw regex generated from the path().
    """
    ...

def get_regex_pattern(urlpattern):
    """
    Get the raw regex out of the urlpattern's RegexPattern or RoutePattern. This is always a regular expression,
    unlike get_original_route above.
    """
    ...

def is_route_pattern(urlpattern):
    ...

def make_url_resolver(regex, urlpatterns):
    ...

def unicode_http_header(value):
    ...

def distinct(queryset, base):
    ...

if 'patch' not in View.http_method_names:
    ...
if markdown is not None and pygments is not None:
    class CodeBlockPreprocessor(Preprocessor):
        pattern = ...
        formatter = ...
        def run(self, lines):
            ...
        
    
    
    def md_filter_add_syntax_highlight(md):
        ...
    
else:
    def md_filter_add_syntax_highlight(md):
        ...
    
SHORT_SEPARATORS = (',', ':')
LONG_SEPARATORS = (', ', ': ')
INDENT_SEPARATORS = (',', ': ')
PY36 = sys.version_info >= (3, 6)
