"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

def get_docs_view(title: Optional[Any] = ..., description: Optional[Any] = ..., schema_url: Optional[Any] = ..., urlconf: Optional[Any] = ..., public: bool = ..., patterns: Optional[Any] = ..., generator_class=..., authentication_classes=..., permission_classes=..., renderer_classes: Optional[Any] = ...):
    ...

def get_schemajs_view(title: Optional[Any] = ..., description: Optional[Any] = ..., schema_url: Optional[Any] = ..., urlconf: Optional[Any] = ..., public: bool = ..., patterns: Optional[Any] = ..., generator_class=..., authentication_classes=..., permission_classes=...):
    ...

def include_docs_urls(title: Optional[Any] = ..., description: Optional[Any] = ..., schema_url: Optional[Any] = ..., urlconf: Optional[Any] = ..., public: bool = ..., patterns: Optional[Any] = ..., generator_class=..., authentication_classes=..., permission_classes=..., renderer_classes: Optional[Any] = ...):
    ...

