"""
This type stub file was generated by pyright.
"""

from django.template.response import SimpleTemplateResponse
from typing import Any, Optional

"""
The Response class in REST framework is similar to HTTPResponse, except that
it is initialized with unrendered data, instead of a pre-rendered string.

The appropriate renderer is called during Django's template response rendering.
"""
class Response(SimpleTemplateResponse):
    """
    An HttpResponse that allows its data to be rendered into
    arbitrary media types.
    """
    def __init__(self, data: Optional[Any] = ..., status: Optional[Any] = ..., template_name: Optional[Any] = ..., headers: Optional[Any] = ..., exception: bool = ..., content_type: Optional[Any] = ...):
        """
        Alters the init arguments slightly.
        For example, drop 'template_name', and instead use 'data'.

        Setting 'renderer' and 'media_type' will typically be deferred,
        For example being set automatically by the `APIView`.
        """
        self.data = ...
        self.template_name = ...
        self.exception = ...
        self.content_type = ...
    
    @property
    def rendered_content(self):
        ...
    
    @property
    def status_text(self):
        """
        Returns reason text corresponding to our HTTP response status code.
        Provided for convenience.
        """
        ...
    
    def __getstate__(self):
        """
        Remove attributes from the response that shouldn't be cached.
        """
        ...
    


