"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

def _get_format_path_converter(suffix_kwarg, allowed):
    class FormatSuffixConverter:
        ...
    
    

def apply_suffix_patterns(urlpatterns, suffix_pattern, suffix_required, suffix_route: Optional[Any] = ...):
    ...

def format_suffix_patterns(urlpatterns, suffix_required: bool = ..., allowed: Optional[Any] = ...):
    """
    Supplement existing urlpatterns with corresponding patterns that also
    include a '.format' suffix.  Retains urlpattern ordering.

    urlpatterns:
        A list of URL patterns.

    suffix_required:
        If `True`, only suffixed URLs will be generated, and non-suffixed
        URLs will not be used.  Defaults to `False`.

    allowed:
        An optional tuple/list of allowed suffixes.  eg ['json', 'api']
        Defaults to `None`, which allows any suffix.
    """
    ...

