sudo: required
language: python
services: docker
before_install:
  - touch .env
  - echo SECRET_KEY=$SECRET_KEY >> .env
  - docker-compose -f docker-compose.dev.yml up --build -d
script:
  - docker-compose -f docker-compose.dev.yml exec web python manage.py test

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: w45k4b/J2TaTYJ0pMeIRvX3+S0heQ0MRcWW/WkHZwW7/Cnp05KZAqsVzV/5wOXdiySdm5LprE65mh9HjWijxybCj1CPkTmlkdcu/cn8nk/cOs5SDjhcjCFJVl1EdwS4NMQ1D840eLb7xO7QiXlWc3rjA2tVRK9n2fEM4SvdB0nASqe1NrFVegDoCOPvNRNKQGJdfE7OkRvSRFIq2zdM3J3nd797/GwdArZK//ipUKXxO8qi5vOYhWHHR+8c2eAaGBPqvOzGJPfYpis9ksXH4Y3m3BclK0HeISIjOqKNfcluUTmFMilZn9m6BvxIVfMZwejsLjs0D94ulKELODjgFOh9wkXQ7VND2ZBCnRyPiq/Vu7HmHpXY53HSbthL5jG8J9Wu5cGXtnIginkzVhjV0jp8JX0SbneRWHXl1UkAJDqhTxtibnVrHy6yDfNa4Wx0vgqS6FFBoIXi5hHx/XHoYd/GLnuvBUImkrXWSelSWQVDBDmsCZFu4B9UAuA22cdP362xMWtnHA++6Nrjbi1pM2xkr13YN1BZH1iCanSWc/uwlKLgTHkYFKg90glq6rGECEpelFiLacnlBH+RhST1DBKDUBMi1O5hFbCYbPTVdgsgQsaEQykz2RzjBy28NEhWaJHXWET4ptPnN5xwY+RVcjEUc8a/m8xNRncSusR8cF/k=
  run:
    - "python manage.py migrate"
  on:
    branch: master
