sudo: required
language: python
services: docker
before_install:
  - touch .env
  - echo SECRET_KEY=$SECRET_KEY >> .env
  # - sudo apt-get install -y ruby-dev
  # - yes | travis encrypt $(heroku auth:token) --add deploy.api_key
  - docker-compose -f docker-compose.dev.yml up --build -d
script:
  - docker-compose -f docker-compose.dev.yml exec web python manage.py test
deploy:
  provider: heroku
  skip_cleanup: true
  app: ai-django-todo
  api_key:
    secure: $HEROKU_API_KEY
  run:
    - python manage.py migrate
  on:
    branch: master
