sudo: required

language: python

services:
  - docker

before_script:
  - sudo setenforce 0
  - sudo /etc/init.d/postgresql stop

before_install:
  - docker-compose up --build -d

script:
  - docker-compose exec web python manage.py makemigrations
  - docker-compose exec web python manage.py migrate
  - docker-compose exec web python manage.py test
