sudo: required

language: python

services: docker

before_install:
  - touch .env
  - echo SECRET_KEY=$SECRET_KEY >> .env
  - docker-compose -f docker-compose.dev.yml up --build

script:
  - docker-compose -f docker-compose.dev.yml exec web python manage.py test
# deploy:
#   provider: script
#   skip_cleanup: true
#   script: heroku login;
#     heroku git:remote --app $HEROKU_APP_NAME;
#     git push heroku master;
#     heroku run python manage.py migrate;
#   on:
#     branch: master
