sudo: required
language: python
services: docker
before_install:
  - touch .env
  - echo SECRET_KEY=$SECRET_KEY >> .env
  - echo DATABASE_URL=$DATABASE_URL >> .env
  - docker-compose up --build -d
script:
  - docker-compose -f docker-compose.yml exec web python manage.py test

deploy:
  provider: script
  skip_cleanup: true
  script: heroku container:login;
    heroku container:push web --app $HEROKU_APP_NAME;
    heroku container:release web --app $HEROKU_APP_NAME;
    heroku run --app $HEROKU_APP_NAME python manage.py migrate
  on:
    branch: master
