sudo: required
language: python
services: docker
before_install:
  - sudo apt-get update
  - sudo apt-get install -y ruby ruby-dev
  - sudo gem install travis
  - yes | travis encrypt $(heroku auth:token) --add deploy.api_key
  - touch .env
  - echo SECRET_KEY=$SECRET_KEY >> .env
  - docker-compose -f docker-compose.dev.yml up --build -d
script:
  - docker-compose -f docker-compose.dev.yml exec web python manage.py test
deploy:
  provider: heroku
  skip_cleanup: true
  app: ai-django-todo
  api_key:
  run:
    - python manage.py migrate
  on:
    branch: master
