version: "3"

volumes:
  dbdata:

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.prod
    volumes:
      - .:/workdir
    command: >
      bash -c 'python manage.py migrate &&
                gunicorn config.wsgi:application --bind 0.0.0.0:8000'
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    build:
      context: docker/db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=hrcwn098
    volumes:
      - dbdata:/var/lib/postgresql/data
    tty: true
    stdin_open: true
