# Generated by Django 3.0.2 on 2020-02-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_name', models.CharField(max_length=200)),
                ('todo_content', models.CharField(max_length=1000)),
                ('todo_done_flag', models.IntegerField(default=0)),
                ('todo_create_date', models.TextField()),
                ('todo_done_date', models.TextField()),
            ],
            options={
                'db_table': 'todo',
            },
        ),
    ]
