# Generated by Django 3.0.3 on 2020-02-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='todo_create_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='todo_done_date',
            new_name='done_date',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='todo_done_flag',
            new_name='done_flag',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='todo_name',
            new_name='name',
        ),
    ]
