# Generated by Django 3.0.3 on 2020-02-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200208_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
