# Generated by Django 3.0.3 on 2020-02-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200213_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.CharField(max_length=10000, verbose_name='ToDo内容'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ToDo名'),
        ),
    ]
