# Generated by Django 3.0.3 on 2020-02-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='done_flag',
        ),
        migrations.AddField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
