"""
This type stub file was generated by pyright.
"""

from collections import OrderedDict
from .generators import BaseSchemaGenerator
from .inspectors import ViewInspector
from typing import Any, Optional

def common_path(paths):
    ...

def is_custom_action(action):
    ...

def distribute_links(obj):
    ...

INSERT_INTO_COLLISION_FMT = """
Schema Naming Collision.

coreapi.Link for URL path {value_url} cannot be inserted into schema.
Position conflicts with coreapi.Link for URL path {target_url}.

Attempted to insert link with keys: {keys}.

Adjust URLs to avoid naming collision or override `SchemaGenerator.get_keys()`
to customise schema structure.
"""
class LinkNode(OrderedDict):
    def __init__(self):
        self.links = ...
        self.methods_counter = ...
    
    def get_available_key(self, preferred_key):
        ...
    


def insert_into(target, keys, value):
    """
    Nested dictionary insertion.

    >>> example = {}
    >>> insert_into(example, ['a', 'b', 'c'], 123)
    >>> example
    LinkNode({'a': LinkNode({'b': LinkNode({'c': LinkNode(links=[123])}}})))
    """
    ...

class SchemaGenerator(BaseSchemaGenerator):
    """
    Original CoreAPI version.
    """
    default_mapping = ...
    coerce_method_names = ...
    def __init__(self, title: Optional[Any] = ..., url: Optional[Any] = ..., description: Optional[Any] = ..., patterns: Optional[Any] = ..., urlconf: Optional[Any] = ..., version: Optional[Any] = ...):
        self.coerce_method_names = ...
    
    def get_links(self, request: Optional[Any] = ...):
        """
        Return a dictionary containing all the links that should be
        included in the API schema.
        """
        ...
    
    def get_schema(self, request: Optional[Any] = ..., public: bool = ...):
        """
        Generate a `coreapi.Document` representing the API schema.
        """
        ...
    
    def get_keys(self, subpath, method, view):
        """
        Return a list of keys that should be used to layout a link within
        the schema document.

        /users/                   ("users", "list"), ("users", "create")
        /users/{pk}/              ("users", "read"), ("users", "update"), ("users", "delete")
        /users/enabled/           ("users", "enabled")  # custom viewset list action
        /users/{pk}/star/         ("users", "star")     # custom viewset detail action
        /users/{pk}/groups/       ("users", "groups", "list"), ("users", "groups", "create")
        /users/{pk}/groups/{pk}/  ("users", "groups", "read"), ("users", "groups", "update"), ("users", "groups", "delete")
        """
        ...
    
    def determine_path_prefix(self, paths):
        """
        Given a list of all paths, return the common prefix which should be
        discounted when generating a schema structure.

        This will be the longest common string that does not include that last
        component of the URL, or the last component before a path parameter.

        For example:

        /api/v1/users/
        /api/v1/users/{pk}/

        The path prefix is '/api/v1'
        """
        ...
    


def field_to_schema(field):
    ...

class AutoSchema(ViewInspector):
    """
    Default inspector for APIView

    Responsible for per-view introspection and schema generation.
    """
    def __init__(self, manual_fields: Optional[Any] = ...):
        """
        Parameters:

        * `manual_fields`: list of `coreapi.Field` instances that
            will be added to auto-generated fields, overwriting on `Field.name`
        """
        ...
    
    def get_link(self, path, method, base_url):
        """
        Generate `coreapi.Link` for self.view, path and method.

        This is the main _public_ access point.

        Parameters:

        * path: Route path for view from URLConf.
        * method: The HTTP request method.
        * base_url: The project "mount point" as given to SchemaGenerator
        """
        ...
    
    def get_path_fields(self, path, method):
        """
        Return a list of `coreapi.Field` instances corresponding to any
        templated path variables.
        """
        ...
    
    def get_serializer_fields(self, path, method):
        """
        Return a list of `coreapi.Field` instances corresponding to any
        request body input, as determined by the serializer class.
        """
        ...
    
    def get_pagination_fields(self, path, method):
        ...
    
    def _allows_filters(self, path, method):
        """
        Determine whether to include filter Fields in schema.

        Default implementation looks for ModelViewSet or GenericAPIView
        actions/methods that cause filtering on the default implementation.

        Override to adjust behaviour for your view.

        Note: Introduced in v3.7: Initially "private" (i.e. with leading underscore)
            to allow changes based on user experience.
        """
        ...
    
    def get_filter_fields(self, path, method):
        ...
    
    def get_manual_fields(self, path, method):
        ...
    
    @staticmethod
    def update_fields(fields, update_with):
        """
        Update list of coreapi.Field instances, overwriting on `Field.name`.

        Utility function to handle replacing coreapi.Field fields
        from a list by name. Used to handle `manual_fields`.

        Parameters:

        * `fields`: list of `coreapi.Field` instances to update
        * `update_with: list of `coreapi.Field` instances to add or replace.
        """
        ...
    
    def get_encoding(self, path, method):
        """
        Return the 'encoding' parameter to use for a given endpoint.
        """
        ...
    


class ManualSchema(ViewInspector):
    """
    Allows providing a list of coreapi.Fields,
    plus an optional description.
    """
    def __init__(self, fields, description=..., encoding: Optional[Any] = ...):
        """
        Parameters:

        * `fields`: list of `coreapi.Field` instances.
        * `description`: String description for view. Optional.
        """
        ...
    
    def get_link(self, path, method, base_url):
        ...
    


def is_enabled():
    """Is CoreAPI Mode enabled?"""
    ...

