"""
This type stub file was generated by pyright.
"""

import re
from typing import Any, Optional

"""
generators.py   # Top-down schema generation

See schemas.__init__.py for package overview.
"""
def get_pk_name(model):
    ...

def is_api_view(callback):
    """
    Return `True` if the given view callback is a REST framework view/viewset.
    """
    ...

def endpoint_ordering(endpoint):
    ...

_PATH_PARAMETER_COMPONENT_RE = re.compile(r'<(?:(?P<converter>[^>:]+):)?(?P<parameter>\w+)>')
class EndpointEnumerator:
    """
    A class to determine the available API endpoints that a project exposes.
    """
    def __init__(self, patterns: Optional[Any] = ..., urlconf: Optional[Any] = ...):
        self.patterns = ...
    
    def get_api_endpoints(self, patterns: Optional[Any] = ..., prefix=...):
        """
        Return a list of all available API endpoints by inspecting the URL conf.
        """
        ...
    
    def get_path_from_regex(self, path_regex):
        """
        Given a URL conf regex, return a URI template string.
        """
        ...
    
    def should_include_endpoint(self, path, callback):
        """
        Return `True` if the given endpoint should be included.
        """
        ...
    
    def get_allowed_methods(self, callback):
        """
        Return a list of the valid HTTP methods for this endpoint.
        """
        ...
    


class BaseSchemaGenerator(object):
    endpoint_inspector_cls = ...
    coerce_path_pk = ...
    def __init__(self, title: Optional[Any] = ..., url: Optional[Any] = ..., description: Optional[Any] = ..., patterns: Optional[Any] = ..., urlconf: Optional[Any] = ..., version: Optional[Any] = ...):
        self.coerce_path_pk = ...
        self.patterns = ...
        self.urlconf = ...
        self.title = ...
        self.description = ...
        self.version = ...
        self.url = ...
        self.endpoints = ...
    
    def _initialise_endpoints(self):
        ...
    
    def _get_paths_and_endpoints(self, request):
        """
        Generate (path, method, view) given (path, method, callback) for paths.
        """
        ...
    
    def create_view(self, callback, method, request: Optional[Any] = ...):
        """
        Given a callback, return an actual view instance.
        """
        ...
    
    def coerce_path(self, path, method, view):
        """
        Coerce {pk} path arguments into the name of the model field,
        where possible. This is cleaner for an external representation.
        (Ie. "this is an identifier", not "this is a database primary key")
        """
        ...
    
    def get_schema(self, request: Optional[Any] = ..., public: bool = ...):
        ...
    
    def has_view_permissions(self, path, method, view):
        """
        Return `True` if the incoming request has the correct view permissions.
        """
        ...
    


