"""
This type stub file was generated by pyright.
"""

from rest_framework.views import APIView

"""
views.py        # Houses `SchemaView`, `APIView` subclass.

See schemas.__init__.py for package overview.
"""
class SchemaView(APIView):
    _ignore_model_permissions = ...
    schema = ...
    renderer_classes = ...
    schema_generator = ...
    public = ...
    def __init__(self, *args, **kwargs):
        ...
    
    def get(self, request, *args, **kwargs):
        ...
    
    def handle_exception(self, exc):
        self.renderer_classes = ...
    


