"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

def get_breadcrumbs(url, request: Optional[Any] = ...):
    """
    Given a url returns a list of breadcrumbs, which are each a
    tuple of (name, url).
    """
    ...

