"""
This type stub file was generated by pyright.
"""

"""
Helper functions that convert strftime formats into more readable representations.
"""
def datetime_formats(formats):
    ...

def date_formats(formats):
    ...

def time_formats(formats):
    ...

def humanize_strptime(format_string):
    ...

