"""
This type stub file was generated by pyright.
"""

from collections import namedtuple

"""
Helper function for returning the field information that is associated
with a model class. This includes returning all the forward and reverse
relationships and their associated metadata.

Usage: `get_field_info(model)` returns a `FieldInfo` instance.
"""
FieldInfo = namedtuple('FieldResult', ['pk', 'fields', 'forward_relations', 'reverse_relations', 'fields_and_pk', 'relations'])
RelationInfo = namedtuple('RelationInfo', ['model_field', 'related_model', 'to_many', 'to_field', 'has_through_model', 'reverse'])
def get_field_info(model):
    """
    Given a model class, returns a `FieldInfo` instance, which is a
    `namedtuple`, containing metadata about the various field types on the model
    including information about their relationships.
    """
    ...

def _get_pk(opts):
    ...

def _get_fields(opts):
    ...

def _get_to_field(field):
    ...

def _get_forward_relationships(opts):
    """
    Returns an `OrderedDict` of field names to `RelationInfo`.
    """
    ...

def _get_reverse_relationships(opts):
    """
    Returns an `OrderedDict` of field names to `RelationInfo`.
    """
    ...

def _merge_fields_and_pk(pk, fields):
    ...

def _merge_relationships(forward_relations, reverse_relations):
    ...

def is_abstract_model(model):
    """
    Given a model class, returns a boolean True if it is abstract and False if it is not.
    """
    ...

